#!/bin/sh
set -e

# grub-mkconfig helper script.
# Copyright (C) 2016,Tianjin KYLIN Information Technology Co., Ltd.
#
# GRUB is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GRUB is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GRUB.  If not, see <http://www.gnu.org/licenses/>.

# Include the GRUB helper library for grub-mkconfig.
. /usr/share/grub/grub-mkconfig_lib

# We want to work in /boot/grub/ only.
test -d /boot/grub; cd /boot/grub

# Set the location of a possibly necessary cache file for the background image.
# NOTE: This MUST BE A DOTFILE to avoid confusing it with user-defined images.
machine=`uname -m`
BACKGROUND_CACHE=".background_cache"
case "$machine" in
  aarch64)
    cat << EOF
set color_normal=white/black
set color_highlight=black/light-gray
EOF
  ;;
  *)
    echo "set color_normal=black/black"
    echo "set color_highlight=black/white"
  ;;
esac
