debian/25_ukui-theme.gschema.override /usr/share/glib-2.0/schemas
debian/chinese /usr/share/initramfs-tools/hooks/
ukui-custom.xml /usr/share/mime/packages
usr/share/plymouth/themes/ubuntukylin-logo/
usr/share/plymouth/themes/ubuntukylin-text/
ukui-icon-theme-basic ukui-icon-theme-classical ukui-icon-theme-default usr/share/icons/
ukui-black usr/share/themes/
ukui-white usr/share/themes/
usr/share/fcitx-qimpanel/skin/ubuntukylin-dark1/
usr/share/fcitx-qimpanel/skin/ubuntukylin-dark2/
usr/share/fcitx-qimpanel/skin/ubuntukylin-light1/
usr/share/fcitx-qimpanel/skin/ubuntukylin-light2/
ukui-grub-theme/06_ukui_theme /etc/grub.d/
usr/share/grub/themes/UKUI/
